apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-express-mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodejs-express-mysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nodejs-express-mysql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nodejs-express-mysql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nodejs-express-mysql
          image: "{{ .Values.image.repository }}" 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: {{ .Values.mysql.hostKey }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: {{ .Values.mysql.userKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: {{ .Values.mysql.passwordKey }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName }}
                  key: {{ .Values.mysql.dbKey }}
