apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-pv
  namespace: flux-system
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql  # Make sure this path exists on your node

