apiVersion: helm.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nodejs-express-app
  namespace: default
spec:
  releaseName: nodejs-express-app
  chart:
    spec:
      chart: ./manifest/nodejs-express-mysql
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      version: "0.1.0"  # Specify the chart version if needed
  values:
    replicaCount: 1
    image:
      repository: fatmanurdocker/nodejs-express-mysql
      tag: 0.1
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
    mysql:
      secretName: mysql-secret
      hostKey: DB_HOST
      userKey: DB_USER
      passwordKey: DB_PASSWORD
      dbKey: DB_NAME
    ingress:
      enabled: false
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80

