apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: nodejs-express-app-update
  namespace: flux-system
spec:
  interval: 1m  # How often Flux checks for image updates
  update:
    path: ./manifest/nodejs-express-mysql/templates/deployment.yaml  # Path to the deployment manifest
    strategy: Setters  # Update the image tag in the deployment.yaml
  sourceRef:
    kind: GitRepository
    name: nodejs-app-repository  # Reference to the GitRepository resource created earlier
