apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: nodejs-express-app-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main  # Git branch where Flux will commit updates
    commit:
      author:
        name: flux-system
        email: flux@mydomain.com
    push:
      branch: main
  update:
    path: ./manifest/nodejs-express-mysql/  # Path where HelmRelease is stored
    strategy: Setters
    regex: 'fatmanurdocker/nodejs-express-mysql:(.*)'  # Image tag regex
