apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nodejs-express-app
  namespace: flux-system
spec:
  interval: 1m
  image: docker.io/fatmanurdocker/nodejs-express-mysql:0.1 # docker image path
