apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs-express-app
  namespace: flux-system
spec:
  interval: 1m
  path:  ./helmrelease  # Path to HelmRelease
  prune: true
  sourceRef:
    kind: GitRepository
    name: nodejs-app-repository
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nodejs-app-nodejs-express-mysql

